import {
  AlertCircle,
  AlertTriangle,
  ArrowDownWideNarrow,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  ArrowUpNarrowWide,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ClipboardList,
  Clock,
  Cloud,
  Code,
  Copy,
  Database,
  Download,
  Edit,
  Eye,
  EyeOff,
  File,
  FileCode,
  FileText,
  Filter,
  Folder,
  FolderOpen,
  Grid3x3,
  Home,
  Image,
  Info,
  List,
  Loader2,
  Maximize,
  Menu,
  Minimize,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Move,
  Music,
  Pause,
  Play,
  Plus,
  Redo2,
  RefreshCw,
  Search,
  Server,
  Settings,
  Columns2,
  Rows2,
  SquareStack,
  Sun,
  Trash2,
  Undo2,
  Upload,
  Video,
  Volume2,
  VolumeX,
  X,
  ZoomIn,
  ZoomOut,
} from 'lucide-react'

// Bundle icons with the desktop app so controls also render without network access.
export const Icons = {
  folder: Folder,
  folderOpen: FolderOpen,
  file: File,
  fileText: FileText,
  image: Image,
  video: Video,
  music: Music,
  home: Home,
  back: ArrowLeft,
  forward: ArrowRight,
  up: ArrowUp,
  refresh: RefreshCw,
  upload: Upload,
  download: Download,
  delete: Trash2,
  edit: Edit,
  copy: Copy,
  move: Move,
  pause: Pause,
  play: Play,
  undo: Undo2,
  redo: Redo2,
  plus: Plus,
  minus: Minus,
  x: X,
  check: Check,
  settings: Settings,
  menu: Menu,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  cloud: Cloud,
  server: Server,
  database: Database,
  loading: Loader2,
  warning: AlertTriangle,
  error: AlertCircle,
  info: Info,
  splitHorizontal: Columns2,
  splitVertical: Rows2,
  maximize: Maximize,
  minimize: Minimize,
  window: SquareStack,
  grid: Grid3x3,
  list: List,
  eye: Eye,
  eyeOff: EyeOff,
  search: Search,
  filter: Filter,
  sort: ArrowUpDown,
  sortAsc: ArrowUpNarrowWide,
  sortDesc: ArrowDownWideNarrow,
  clock: Clock,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  code: Code,
  fileCode: FileCode,
  volume: Volume2,
  volumeX: VolumeX,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  sun: Sun,
  moon: Moon,
  monitor: Monitor,
  clipboard: ClipboardList,
  loader: Loader2,
  alertTriangle: AlertTriangle,
}
